<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();

        $userList = [
            [
                'name' => 'Giám đốc cấp tỉnh',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 2,
                'position_id' => 11,
            ],
            [
                'name' => 'Phó Giám đốc cấp tỉnh',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 2,
                'position_id' => 10,
            ],
            [
                'name' => 'Trưởng tỉnh 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 9,
            ],
            [
                'name' => 'Phó tỉnh 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 8,
            ],
            [
                'name' => 'Văn thư tỉnh 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 7,
                'code' => 'td100000'
            ],
            [
                'name' => 'Văn thư tỉnh 2',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 7,
            ],
            [
                'name' => 'Nhân viên tỉnh 1-1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => 'td100001'
            ],
            [
                'name' => 'Nhân viên tỉnh 1-2',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => 'kt100000'
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 3,
                'position_id' => 6,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true
            ],

            [
                'name' => 'Giám đốc huyện 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 5,
            ],
            [
                'name' => 'Phó giám đốc huyện 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 4,
            ],
            [
                'name' => 'Tổ trưởng huyện 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 3,
                'code' => 'td200000'
            ],
            [
                'name' => 'Văn thư trưởng huyện 1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 1,
                'code' => 'td200001'
            ],
            [
                'name' => 'Văn thư trưởng huyện 2',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 1,
            ],
            [
                'name' => 'Nhân viên huyện 1-1',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => 'kt200000'
            ],
            [
                'name' => 'Nhân viên huyện 1-2',
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
            [
                'name' => $faker->unique()->name,
                'email' => $faker->unique()->email,
                'password' => bcrypt('12345678'),
                'department_id' => 4,
                'position_id' => 2,
                'code' => $faker->unique()->countryCode,
                'can_assign_job' => true,
            ],
        ];

        foreach ($userList as $user) {
            User::create($user);
        }
    }
}
